services:
    medhead_ihm:
        image: pierre9820/medhead-ihm:latest
        container_name: medhead-ihm
        restart: always
        environment:
            - GOOGLE_MAP_API_KEY=AIzaSyB86d0Y3Drd6HxhN2aYDI-hnkLf6rw1WmE
        ports:
            - '8082:8080'
        volumes:
            - medhead_ihm:/app
volumes:
    medhead_ihm:
        driver: local